import { createRouter, createWebHistory } from 'vue-router'
import { useAuth } from '@/composables/useAuth'

const routes = [
  {
    path: '/login',
    name: 'Login',
    component: () => import('@/views/Login.vue'),
    meta: { guest: true },
  },
  {
    path: '/',
    component: () => import('@/layouts/MainLayout.vue'),
    meta: { requiresAuth: true },
    children: [
      { path: '', name: 'Home', component: () => import('@/views/Home.vue') },
      { path: 'my', name: 'MyIndex', component: () => import('@/views/my/MyIndex.vue') },
      { path: 'my/todo', name: 'MyTodo', component: () => import('@/views/my/MyTodo.vue') },
      { path: 'my/task', name: 'MyTask', component: () => import('@/views/my/MyTask.vue') },
      { path: 'my/bug', name: 'MyBug', component: () => import('@/views/my/MyBug.vue') },
      { path: 'my/story', name: 'MyStory', component: () => import('@/views/my/MyStory.vue') },
      { path: 'my/dynamic', name: 'MyDynamic', component: () => import('@/views/my/MyDynamic.vue') },
      { path: 'my/score', name: 'MyScore', component: () => import('@/views/my/MyScore.vue') },
      { path: 'my/work', name: 'MyWork', component: () => import('@/views/my/MyWork.vue') },
      { path: 'my/calendar', name: 'MyCalendar', component: () => import('@/views/my/MyCalendar.vue') },
      { path: 'my/profile', name: 'MyProfile', component: () => import('@/views/my/MyProfile.vue') },
      { path: 'my/preference', name: 'MyPreference', component: () => import('@/views/my/MyPreference.vue') },
      { path: 'project', name: 'ProjectList', component: () => import('@/views/project/ProjectList.vue') },
      { path: 'project/create', name: 'ProjectCreate', component: () => import('@/views/project/ProjectCreate.vue') },
      { path: 'project/edit/:id', name: 'ProjectEdit', component: () => import('@/views/project/ProjectEdit.vue') },
      { path: 'project/:id/team', name: 'ProjectTeam', component: () => import('@/views/project/ProjectTeam.vue') },
      { path: 'project/:id/products', name: 'ProjectProducts', component: () => import('@/views/project/ProjectProducts.vue') },
      { path: 'project/:id', name: 'ProjectView', component: () => import('@/views/project/ProjectView.vue') },
      { path: 'execution', name: 'ExecutionList', component: () => import('@/views/execution/ExecutionList.vue') },
      { path: 'execution/create', name: 'ExecutionCreate', component: () => import('@/views/execution/ExecutionCreate.vue') },
      { path: 'execution/edit/:id', name: 'ExecutionEdit', component: () => import('@/views/execution/ExecutionEdit.vue') },
      { path: 'execution/:id/team', name: 'ExecutionTeam', component: () => import('@/views/execution/ExecutionTeam.vue') },
      { path: 'execution/:id/dynamic', name: 'ExecutionDynamic', component: () => import('@/views/execution/ExecutionDynamic.vue') },
      { path: 'execution/:id', name: 'ExecutionView', component: () => import('@/views/execution/ExecutionView.vue') },
      { path: 'todo', name: 'TodoList', component: () => import('@/views/todo/TodoList.vue') },
      { path: 'todo/create', name: 'TodoCreate', component: () => import('@/views/todo/TodoCreate.vue') },
      { path: 'todo/edit/:id', name: 'TodoEdit', component: () => import('@/views/todo/TodoEdit.vue') },
      { path: 'todo/:id', name: 'TodoView', component: () => import('@/views/todo/TodoView.vue') },
      { path: 'productplan', name: 'ProductPlanList', component: () => import('@/views/productplan/ProductPlanList.vue') },
      { path: 'productplan/create', name: 'ProductPlanCreate', component: () => import('@/views/productplan/ProductPlanCreate.vue') },
      { path: 'productplan/edit/:id', name: 'ProductPlanEdit', component: () => import('@/views/productplan/ProductPlanEdit.vue') },
      { path: 'productplan/:id', name: 'ProductPlanView', component: () => import('@/views/productplan/ProductPlanView.vue') },
      { path: 'program', name: 'ProgramList', component: () => import('@/views/program/ProgramList.vue') },
      { path: 'program/create', name: 'ProgramCreate', component: () => import('@/views/program/ProgramCreate.vue') },
      { path: 'program/edit/:id', name: 'ProgramEdit', component: () => import('@/views/program/ProgramEdit.vue') },
      { path: 'program/:id', name: 'ProgramView', component: () => import('@/views/program/ProgramView.vue') },
      { path: 'kanban', name: 'KanbanSpaceList', component: () => import('@/views/kanban/KanbanSpaceList.vue') },
      { path: 'kanban/space/create', name: 'KanbanSpaceCreate', component: () => import('@/views/kanban/KanbanSpaceCreate.vue') },
      { path: 'kanban/space/edit/:id', name: 'KanbanSpaceEdit', component: () => import('@/views/kanban/KanbanSpaceEdit.vue') },
      { path: 'kanban/space/:id', name: 'KanbanSpaceView', component: () => import('@/views/kanban/KanbanSpaceView.vue') },
      { path: 'kanban/create', name: 'KanbanCreate', component: () => import('@/views/kanban/KanbanCreate.vue') },
      { path: 'kanban/board/:id', name: 'KanbanBoard', component: () => import('@/views/kanban/KanbanBoard.vue') },
      { path: 'report', name: 'ReportIndex', component: () => import('@/views/report/ReportIndex.vue') },
      { path: 'report/remind', name: 'ReportRemind', component: () => import('@/views/report/ReportRemind.vue') },
      { path: 'metric', name: 'MetricList', component: () => import('@/views/metric/MetricList.vue') },
      { path: 'metric/:id', name: 'MetricView', component: () => import('@/views/metric/MetricView.vue') },
      { path: 'search', name: 'SearchIndex', component: () => import('@/views/search/SearchIndex.vue') },
      { path: 'testreport', name: 'TestReportList', component: () => import('@/views/testreport/TestReportList.vue') },
      { path: 'testreport/create', name: 'TestReportCreate', component: () => import('@/views/testreport/TestReportCreate.vue') },
      { path: 'testreport/edit/:id', name: 'TestReportEdit', component: () => import('@/views/testreport/TestReportEdit.vue') },
      { path: 'testreport/:id', name: 'TestReportView', component: () => import('@/views/testreport/TestReportView.vue') },
      { path: 'testsuite', name: 'TestSuiteList', component: () => import('@/views/testsuite/TestSuiteList.vue') },
      { path: 'testsuite/create', name: 'TestSuiteCreate', component: () => import('@/views/testsuite/TestSuiteCreate.vue') },
      { path: 'testsuite/edit/:id', name: 'TestSuiteEdit', component: () => import('@/views/testsuite/TestSuiteEdit.vue') },
      { path: 'testsuite/:id', name: 'TestSuiteView', component: () => import('@/views/testsuite/TestSuiteView.vue') },
      { path: 'branch', name: 'BranchList', component: () => import('@/views/branch/BranchList.vue') },
      { path: 'branch/create', name: 'BranchCreate', component: () => import('@/views/branch/BranchCreate.vue') },
      { path: 'branch/edit/:id', name: 'BranchEdit', component: () => import('@/views/branch/BranchEdit.vue') },
      { path: 'branch/:id', name: 'BranchView', component: () => import('@/views/branch/BranchView.vue') },
      { path: 'tree', name: 'TreeBrowse', component: () => import('@/views/tree/TreeBrowse.vue') },
      { path: 'tree/edit/:id', name: 'TreeEdit', component: () => import('@/views/tree/TreeEdit.vue') },
      { path: 'caselib', name: 'CaselibList', component: () => import('@/views/caselib/CaselibList.vue') },
      { path: 'caselib/create', name: 'CaselibCreate', component: () => import('@/views/caselib/CaselibCreate.vue') },
      { path: 'caselib/edit/:id', name: 'CaselibEdit', component: () => import('@/views/caselib/CaselibEdit.vue') },
      { path: 'caselib/:id', name: 'CaselibView', component: () => import('@/views/caselib/CaselibView.vue') },
      { path: 'chart', name: 'ChartList', component: () => import('@/views/chart/ChartList.vue') },
      { path: 'chart/create', name: 'ChartCreate', component: () => import('@/views/chart/ChartCreate.vue') },
      { path: 'chart/edit/:id', name: 'ChartEdit', component: () => import('@/views/chart/ChartEdit.vue') },
      { path: 'chart/:id', name: 'ChartView', component: () => import('@/views/chart/ChartView.vue') },
      { path: 'weekly', name: 'WeeklyList', component: () => import('@/views/weekly/WeeklyList.vue') },
      { path: 'weekly/create', name: 'WeeklyCreate', component: () => import('@/views/weekly/WeeklyCreate.vue') },
      { path: 'weekly/edit/:id', name: 'WeeklyEdit', component: () => import('@/views/weekly/WeeklyEdit.vue') },
      { path: 'weekly/:id', name: 'WeeklyView', component: () => import('@/views/weekly/WeeklyView.vue') },
      { path: 'admin', name: 'AdminIndex', component: () => import('@/views/admin/AdminIndex.vue') },
      { path: 'admin/config', name: 'AdminConfig', component: () => import('@/views/admin/AdminConfig.vue') },
      { path: 'admin/safe', name: 'AdminSafe', component: () => import('@/views/admin/AdminSafe.vue') },
      { path: 'admin/log', name: 'AdminLog', component: () => import('@/views/admin/AdminLog.vue') },
      { path: 'admin/backup', name: 'AdminBackup', component: () => import('@/views/admin/AdminBackup.vue') },
      { path: 'admin/cron', name: 'AdminCron', component: () => import('@/views/admin/AdminCron.vue') },
      { path: 'admin/webhook', name: 'AdminWebhook', component: () => import('@/views/admin/AdminWebhook.vue') },
      { path: 'admin/webhook/:id', name: 'AdminWebhookView', component: () => import('@/views/admin/AdminWebhookView.vue') },
      { path: 'admin/message', name: 'AdminMessage', component: () => import('@/views/admin/AdminMessage.vue') },
      { path: 'admin/cache', name: 'AdminCache', component: () => import('@/views/admin/AdminCache.vue') },
      { path: 'admin/upgrade', name: 'AdminUpgrade', component: () => import('@/views/admin/AdminUpgrade.vue') },
      { path: 'admin/tutorial', name: 'AdminTutorial', component: () => import('@/views/admin/AdminTutorial.vue') },
      { path: 'admin/sso', name: 'AdminSso', component: () => import('@/views/admin/AdminSso.vue') },
      { path: 'admin/sso/:id', name: 'AdminSsoView', component: () => import('@/views/admin/AdminSsoView.vue') },
      { path: 'stage', name: 'StageList', component: () => import('@/views/stage/StageList.vue') },
      { path: 'stage/create', name: 'StageCreate', component: () => import('@/views/stage/StageCreate.vue') },
      { path: 'stage/edit/:id', name: 'StageEdit', component: () => import('@/views/stage/StageEdit.vue') },
      { path: 'stage/:id', name: 'StageView', component: () => import('@/views/stage/StageView.vue') },
      { path: 'serverroom', name: 'ServerroomList', component: () => import('@/views/serverroom/ServerroomList.vue') },
      { path: 'serverroom/:id', name: 'ServerroomView', component: () => import('@/views/serverroom/ServerroomView.vue') },
      { path: 'pipeline', name: 'PipelineList', component: () => import('@/views/pipeline/PipelineList.vue') },
      { path: 'pipeline/:id', name: 'PipelineView', component: () => import('@/views/pipeline/PipelineView.vue') },
      { path: 'requirement', name: 'RequirementList', component: () => import('@/views/requirement/RequirementList.vue') },
      { path: 'requirement/:id', name: 'RequirementView', component: () => import('@/views/requirement/RequirementView.vue') },
      { path: 'programplan', name: 'ProgramplanList', component: () => import('@/views/programplan/ProgramplanList.vue') },
      { path: 'programplan/:id', name: 'ProgramplanView', component: () => import('@/views/programplan/ProgramplanView.vue') },
      { path: 'dataview', name: 'DataviewList', component: () => import('@/views/dataview/DataviewList.vue') },
      { path: 'dataview/:id', name: 'DataviewView', component: () => import('@/views/dataview/DataviewView.vue') },
      { path: 'dimension', name: 'DimensionList', component: () => import('@/views/dimension/DimensionList.vue') },
      { path: 'dimension/:id', name: 'DimensionView', component: () => import('@/views/dimension/DimensionView.vue') },
      { path: 'entry', name: 'EntryList', component: () => import('@/views/entry/EntryList.vue') },
      { path: 'entry/:id', name: 'EntryView', component: () => import('@/views/entry/EntryView.vue') },
      { path: 'stakeholder', name: 'StakeholderList', component: () => import('@/views/stakeholder/StakeholderList.vue') },
      { path: 'stakeholder/:id', name: 'StakeholderView', component: () => import('@/views/stakeholder/StakeholderView.vue') },
      { path: 'screen', name: 'ScreenList', component: () => import('@/views/screen/ScreenList.vue') },
      { path: 'screen/:id', name: 'ScreenView', component: () => import('@/views/screen/ScreenView.vue') },
      { path: 'system', name: 'SystemInfo', component: () => import('@/views/system/SystemInfo.vue') },
      { path: 'setting', name: 'SettingConfig', component: () => import('@/views/setting/SettingConfig.vue') },
      { path: 'product', name: 'ProductList', component: () => import('@/views/product/ProductList.vue') },
      { path: 'product/create', name: 'ProductCreate', component: () => import('@/views/product/ProductCreate.vue') },
      { path: 'product/edit/:id', name: 'ProductEdit', component: () => import('@/views/product/ProductEdit.vue') },
      { path: 'product/:id', name: 'ProductView', component: () => import('@/views/product/ProductView.vue') },
      { path: 'task', name: 'TaskList', component: () => import('@/views/task/TaskList.vue') },
      { path: 'task/create', name: 'TaskCreate', component: () => import('@/views/task/TaskCreate.vue') },
      { path: 'task/edit/:id', name: 'TaskEdit', component: () => import('@/views/task/TaskEdit.vue') },
      { path: 'task/:id', name: 'TaskView', component: () => import('@/views/task/TaskView.vue') },
      { path: 'bug', name: 'BugList', component: () => import('@/views/bug/BugList.vue') },
      { path: 'bug/create', name: 'BugCreate', component: () => import('@/views/bug/BugCreate.vue') },
      { path: 'bug/edit/:id', name: 'BugEdit', component: () => import('@/views/bug/BugEdit.vue') },
      { path: 'bug/:id', name: 'BugView', component: () => import('@/views/bug/BugView.vue') },
      { path: 'story', name: 'StoryList', component: () => import('@/views/story/StoryList.vue') },
      { path: 'story/create', name: 'StoryCreate', component: () => import('@/views/story/StoryCreate.vue') },
      { path: 'story/edit/:id', name: 'StoryEdit', component: () => import('@/views/story/StoryEdit.vue') },
      { path: 'story/:id', name: 'StoryView', component: () => import('@/views/story/StoryView.vue') },
      { path: 'build', name: 'BuildList', component: () => import('@/views/build/BuildList.vue') },
      { path: 'build/create', name: 'BuildCreate', component: () => import('@/views/build/BuildCreate.vue') },
      { path: 'build/edit/:id', name: 'BuildEdit', component: () => import('@/views/build/BuildEdit.vue') },
      { path: 'build/:id', name: 'BuildView', component: () => import('@/views/build/BuildView.vue') },
      { path: 'repo', name: 'RepoList', component: () => import('@/views/repo/RepoList.vue') },
      { path: 'repo/:id', name: 'RepoView', component: () => import('@/views/repo/RepoView.vue') },
      { path: 'release', name: 'ReleaseList', component: () => import('@/views/release/ReleaseList.vue') },
      { path: 'release/create', name: 'ReleaseCreate', component: () => import('@/views/release/ReleaseCreate.vue') },
      { path: 'release/edit/:id', name: 'ReleaseEdit', component: () => import('@/views/release/ReleaseEdit.vue') },
      { path: 'release/:id', name: 'ReleaseView', component: () => import('@/views/release/ReleaseView.vue') },
      { path: 'testcase', name: 'TestCaseList', component: () => import('@/views/testcase/TestCaseList.vue') },
      { path: 'testcase/:id', name: 'TestCaseView', component: () => import('@/views/testcase/TestCaseView.vue') },
      { path: 'testtask', name: 'TestTaskList', component: () => import('@/views/testtask/TestTaskList.vue') },
      { path: 'testtask/:id', name: 'TestTaskView', component: () => import('@/views/testtask/TestTaskView.vue') },
      { path: 'doc', name: 'DocList', component: () => import('@/views/doc/DocList.vue') },
      { path: 'doc/:id', name: 'DocView', component: () => import('@/views/doc/DocView.vue') },
      { path: 'company', name: 'CompanyList', component: () => import('@/views/company/CompanyList.vue') },
      { path: 'company/:id', name: 'CompanyView', component: () => import('@/views/company/CompanyView.vue') },
      { path: 'dept', name: 'DeptTree', component: () => import('@/views/dept/DeptTree.vue') },
      { path: 'group', name: 'GroupList', component: () => import('@/views/group/GroupList.vue') },
      { path: 'group/:id', name: 'GroupView', component: () => import('@/views/group/GroupView.vue') },
      { path: 'holiday', name: 'HolidayList', component: () => import('@/views/holiday/HolidayList.vue') },
      { path: 'holiday/create', name: 'HolidayCreate', component: () => import('@/views/holiday/HolidayCreate.vue') },
      { path: 'holiday/edit/:id', name: 'HolidayEdit', component: () => import('@/views/holiday/HolidayEdit.vue') },
      { path: 'extension', name: 'ExtensionList', component: () => import('@/views/extension/ExtensionList.vue') },
      { path: 'design', name: 'DesignList', component: () => import('@/views/design/DesignList.vue') },
      { path: 'feedback', name: 'FeedbackList', component: () => import('@/views/feedback/FeedbackList.vue') },
      { path: 'mr', name: 'MrList', component: () => import('@/views/mr/MrList.vue') },
      { path: 'host', name: 'HostList', component: () => import('@/views/host/HostList.vue') },
      { path: 'host/create', name: 'HostCreate', component: () => import('@/views/host/HostCreate.vue') },
      { path: 'host/edit/:id', name: 'HostEdit', component: () => import('@/views/host/HostEdit.vue') },
      { path: 'host/:id', name: 'HostView', component: () => import('@/views/host/HostView.vue') },
      { path: 'jenkins', name: 'JenkinsList', component: () => import('@/views/jenkins/JenkinsList.vue') },
      { path: 'jenkins/create', name: 'JenkinsCreate', component: () => import('@/views/jenkins/JenkinsCreate.vue') },
      { path: 'jenkins/edit/:id', name: 'JenkinsEdit', component: () => import('@/views/jenkins/JenkinsEdit.vue') },
      { path: 'jenkins/:id', name: 'JenkinsView', component: () => import('@/views/jenkins/JenkinsView.vue') },
      { path: 'sonarqube', name: 'SonarqubeList', component: () => import('@/views/sonarqube/SonarqubeList.vue') },
      { path: 'sonarqube/create', name: 'SonarqubeCreate', component: () => import('@/views/sonarqube/SonarqubeCreate.vue') },
      { path: 'sonarqube/edit/:id', name: 'SonarqubeEdit', component: () => import('@/views/sonarqube/SonarqubeEdit.vue') },
      { path: 'sonarqube/:id', name: 'SonarqubeView', component: () => import('@/views/sonarqube/SonarqubeView.vue') },
      { path: 'user', name: 'UserList', component: () => import('@/views/user/UserList.vue') },
      { path: 'user/create', name: 'UserCreate', component: () => import('@/views/user/UserCreate.vue') },
      { path: 'user/batchCreate', name: 'UserBatchCreate', component: () => import('@/views/user/UserBatchCreate.vue') },
      { path: 'user/batchEdit', name: 'UserBatchEdit', component: () => import('@/views/user/UserBatchEdit.vue') },
      { path: 'user/edit/:id', name: 'UserEdit', component: () => import('@/views/user/UserEdit.vue') },
      {
        path: 'user/:id',
        name: 'UserView',
        component: () => import('@/views/user/UserView.vue'),
        children: [
          { path: '', redirect: { name: 'UserTodo' } },
          { path: 'todo', name: 'UserTodo', component: () => import('@/views/user/UserTodo.vue') },
          { path: 'task', name: 'UserTask', component: () => import('@/views/user/UserTask.vue') },
          { path: 'bug', name: 'UserBug', component: () => import('@/views/user/UserBug.vue') },
          { path: 'story', name: 'UserStory', component: () => import('@/views/user/UserStory.vue') },
          { path: 'testtask', name: 'UserTesttask', component: () => import('@/views/user/UserTesttask.vue') },
          { path: 'testcase', name: 'UserTestcase', component: () => import('@/views/user/UserTestcase.vue') },
          { path: 'execution', name: 'UserExecution', component: () => import('@/views/user/UserExecution.vue') },
          { path: 'dynamic', name: 'UserDynamic', component: () => import('@/views/user/UserDynamic.vue') },
          { path: 'profile', name: 'UserProfile', component: () => import('@/views/user/UserProfile.vue') },
        ],
      },
    ],
  },
]

const router = createRouter({
  history: createWebHistory(),
  routes,
})

router.beforeEach((to, from, next) => {
  const { token } = useAuth()
  if (to.meta.requiresAuth && !token.value) {
    next({ name: 'Login', query: { redirect: to.fullPath } })
  } else if (to.meta.guest && token.value) {
    next({ name: 'Home' })
  } else {
    next()
  }
})

export default router
